/**
 * PlannerPage.jsx — Grand Line AI Planner: full daily schedule view.
 */
import React, { useEffect, useState } from 'react';
import api from '../api/axios';
import toast from 'react-hot-toast';
import { Brain, Zap, CheckCircle2, Circle, RefreshCw, Clock } from 'lucide-react';

const CATEGORY_COLORS = {
  study: '#00ff9d', haki_training: '#ff6b35', class: '#0070f3',
  break: '#8b949e', review: '#aa44ff', coding: '#00d4ff', rest: '#484f58', other: '#8b949e',
};

const CATEGORY_LABELS = {
  study: '📚 Study', haki_training: '⚔️ Training', class: '🎓 Class',
  break: '☕ Break', review: '🔍 Review', coding: '💻 Coding',
  rest: '😴 Rest', other: '📌 Other',
};

export default function PlannerPage() {
  const [plan, setPlan] = useState(null);
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);
  const [selectedDate, setSelectedDate] = useState(new Date().toISOString().split('T')[0]);

  useEffect(() => {
    loadPlan(selectedDate);
  }, [selectedDate]);

  const loadPlan = async (date) => {
    setLoading(true);
    try {
      const endpoint = date === new Date().toISOString().split('T')[0]
        ? '/planner/today'
        : `/planner/${date}`;
      const { data } = await api.get(endpoint);
      setPlan(data.plan);
    } catch (_) {
      setPlan(null);
    }
    setLoading(false);
  };

  const handleGenerate = async () => {
    setGenerating(true);
    try {
      const { data } = await api.post('/planner/generate');
      setPlan(data.plan);
      toast.success('⚓ Grand Line Plan generated by Gemini!');
    } catch (err) {
      toast.error(err.response?.data?.message || 'Failed to generate plan.');
    }
    setGenerating(false);
  };

  const handleCompleteItem = async (itemId) => {
    if (!plan) return;
    try {
      const { data } = await api.patch(`/planner/${plan._id}/item/${itemId}`);
      setPlan(data.plan);
    } catch (_) {
      toast.error('Failed to update item.');
    }
  };

  const completedCount = plan?.schedule?.filter(i => i.isCompleted).length || 0;
  const totalCount = plan?.schedule?.length || 0;
  const progressPct = totalCount > 0 ? (completedCount / totalCount) * 100 : 0;

  return (
    <div className="animate-fade-in">
      {/* ── Header ─────────────────────────────────────────────────────── */}
      <div className="page-header">
        <div>
          <h1 className="page-title">🧭 Grand Line Plan</h1>
          <p className="page-subtitle">AI-powered daily schedule</p>
        </div>
        <div style={{ display: 'flex', gap: 8, alignItems: 'center' }}>
          <input
            type="date"
            value={selectedDate}
            onChange={e => setSelectedDate(e.target.value)}
            className="input"
            style={{ width: 160, fontSize: '0.8rem' }}
          />
          <button
            className="btn btn-primary btn-sm"
            onClick={handleGenerate}
            disabled={generating}
          >
            {generating ? <RefreshCw size={14} style={{ animation: 'spin 1s linear infinite' }} /> : <Zap size={14} />}
            {generating ? 'Generating...' : 'Generate'}
          </button>
        </div>
      </div>

      {loading ? (
        <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
          {[1,2,3,4,5].map(i => <div key={i} className="skeleton" style={{ height: 64, borderRadius: 8 }} />)}
        </div>
      ) : !plan ? (
        <div style={{
          display: 'flex', flexDirection: 'column', alignItems: 'center',
          justifyContent: 'center', gap: 16, height: '50vh', textAlign: 'center',
        }}>
          <Brain size={48} color="var(--text-muted)" />
          <div>
            <h2 style={{ fontFamily: 'var(--font-display)', marginBottom: 8 }}>No Plan for {selectedDate}</h2>
            <p style={{ color: 'var(--text-muted)', maxWidth: 400 }}>
              The AI planner runs automatically at 5:00 AM IST.
              Click "Generate" to create one now.
            </p>
          </div>
          <button className="btn btn-primary" onClick={handleGenerate} disabled={generating}>
            {generating ? 'Generating...' : '⚡ Generate Plan Now'}
          </button>
        </div>
      ) : (
        <div>
          {/* Progress */}
          <div className="card" style={{ marginBottom: 16 }}>
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 10 }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
                <Brain size={16} color="var(--zoro-500)" />
                <span style={{ fontWeight: 600, fontSize: '0.9rem' }}>
                  {selectedDate === new Date().toISOString().split('T')[0] ? "Today's Plan" : `Plan for ${selectedDate}`}
                </span>
              </div>
              <span style={{ fontSize: '0.8rem', color: 'var(--zoro-500)', fontWeight: 700 }}>
                {completedCount}/{totalCount} done
              </span>
            </div>
            <div className="progress-bar">
              <div className="progress-bar-fill" style={{ width: `${progressPct}%` }} />
            </div>

            {/* AI Reasoning */}
            {plan.aiReasoning && (
              <div style={{
                marginTop: 12, padding: '10px 12px',
                background: 'rgba(0,255,157,0.04)', border: '1px solid rgba(0,255,157,0.1)',
                borderRadius: 6, fontSize: '0.8rem', color: 'var(--text-muted)', fontStyle: 'italic',
              }}>
                💡 Gemini says: {plan.aiReasoning}
              </div>
            )}
          </div>

          {/* Schedule Items */}
          <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
            {plan.schedule?.map((item) => (
              <div
                key={item._id}
                className="schedule-item"
                onClick={() => handleCompleteItem(item._id)}
                style={{
                  opacity: item.isCompleted ? 0.6 : 1,
                  cursor: 'pointer',
                  borderLeft: `3px solid ${CATEGORY_COLORS[item.category] || '#666'}`,
                }}
              >
                {/* Time */}
                <div style={{ minWidth: 90 }}>
                  <div className="schedule-time" style={{ fontSize: '0.75rem', display: 'block' }}>
                    {item.time}
                  </div>
                  <div style={{ fontSize: '0.65rem', color: 'var(--text-muted)' }}>
                    {item.duration}m
                  </div>
                </div>

                {/* Content */}
                <div style={{ flex: 1, minWidth: 0 }}>
                  <div style={{
                    fontWeight: 600, fontSize: '0.875rem',
                    textDecoration: item.isCompleted ? 'line-through' : 'none',
                    color: item.isCompleted ? 'var(--text-muted)' : 'var(--text-primary)',
                    overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap',
                  }}>
                    {item.title}
                  </div>
                  <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginTop: 2 }}>
                    <span style={{
                      fontSize: '0.65rem', fontWeight: 600, color: CATEGORY_COLORS[item.category],
                    }}>
                      {CATEGORY_LABELS[item.category] || item.category}
                    </span>
                    {item.description && (
                      <span style={{ fontSize: '0.7rem', color: 'var(--text-muted)', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>
                        {item.description}
                      </span>
                    )}
                  </div>
                </div>

                {/* Completion indicator */}
                <div style={{ flexShrink: 0 }}>
                  {item.isCompleted
                    ? <CheckCircle2 size={18} color="var(--zoro-500)" style={{ filter: 'drop-shadow(0 0 6px rgba(0,255,157,0.5))' }} />
                    : <Circle size={18} color="var(--text-muted)" />
                  }
                </div>
              </div>
            ))}
          </div>

          {/* Context snapshot */}
          {plan.contextSnapshot && (
            <div className="card" style={{ marginTop: 16, padding: 14 }}>
              <div style={{ fontSize: '0.75rem', color: 'var(--text-muted)', fontWeight: 600, marginBottom: 8 }}>
                CONTEXT USED BY GEMINI
              </div>
              <div style={{ display: 'flex', gap: 12, flexWrap: 'wrap', fontSize: '0.75rem', color: 'var(--text-secondary)' }}>
                <span>📋 {plan.contextSnapshot.unfinishedTaskCount || 0} unfinished tasks</span>
                <span>🎓 {plan.contextSnapshot.classCount || 0} classes</span>
                <span>⚔️ {plan.contextSnapshot.pendingHabits?.length || 0} pending habits</span>
                {plan.contextSnapshot.nextSkillTopic && (
                  <span>📚 Next: {plan.contextSnapshot.nextSkillTopic?.slice(0,40)}</span>
                )}
              </div>
            </div>
          )}
        </div>
      )}
    </div>
  );
}
